https://testing-h5.yongche.org/Ajax/Rechargerebate/getActiveInfo?time=

{
    "code":200,
    "msg":"ok",
    "result":{
        "is_join_rebate":0,
        "is_rebate_money_limit":2,
        "is_black":0,
        "risk":true,
        "project_id":252,
        "project_tags":[
            {
                "tag_id":670,
                "tag_banner":"",
                "tag_picture":"",
                "show_name":"",
                "recharge":100,
                "activity_id":1053,
                "tag_order":1,
                "percent":0,
                "otherRewards":""
            },
            {
                "tag_id":671,
                "tag_banner":"",
                "tag_picture":"",
                "show_name":"",
                "recharge":300,
                "activity_id":1053,
                "tag_order":2,
                "percent":0,
                "otherRewards":""
            },
            {
                "levels":[
                    {
                        "min_price":0,
                        "max_price":99999999,
                        "percent":0,
                        "tag_banner":"",
                        "otherReward":""
                    }
                ],
                "tag_id":672,
                "tag_banner":"",
                "tag_picture":"",
                "show_name":"",
                "recharge":0,
                "activity_id":1053,
                "tag_order":3,
                "percent":0,
                "otherRewards":""
            }
        ],
        "no_rebate_price":100,
        "project_document":null,
        "rebate_money_limit":100
    }
}