_app_token_v3=EMZZYJ8vQN9uB_zKaiy7q574cF_w19hUC2gO0mrPNzs; 
https://h5.yongche.com/Ajax/Rechargerebate/getActiveInfo?time=Fri,%2024%20Aug%202018%2002:29:05%20GMT
{
    "code":200,
    "msg":"ok",
    "result":{
        "is_join_rebate":0,
        "is_rebate_money_limit":2,
        "is_black":0,
        "risk":true,
        "project_id":554,
        "project_tags":[
            {
                "tag_id":4448,
                "tag_banner":"",
                "tag_picture":"https://i3.yongche.name/media/g3/M04/01/24/rBEDAlt-NHyIckZlAAIn58iurf4AAAnawMP-eEAAif_828.png",
                "show_name":"",
                "recharge":100,
                "activity_id":1053,
                "tag_order":1,
                "percent":40,
                "otherRewards":""
            },
            {
                "tag_id":4449,
                "tag_banner":"",
                "tag_picture":"https://i3.yongche.name/media/g3/M04/01/24/rBEDAlt-NI2IKfHTAAIzxJ_Ym7EAAAnawOGe8oAAjPc299.png",
                "show_name":"",
                "recharge":200,
                "activity_id":1053,
                "tag_order":2,
                "percent":40,
                "otherRewards":""
            },
            {
                "tag_id":4450,
                "tag_banner":"",
                "tag_picture":"https://i1.yongche.name/media/g3/M04/01/24/rBEDA1t-NJuIXJWLAAIwL-PvcRkAAAnawP5ETkAAjBH635.png",
                "show_name":"",
                "recharge":300,
                "activity_id":1053,
                "tag_order":3,
                "percent":40,
                "otherRewards":""
            },
            {
                "tag_id":4451,
                "tag_banner":"",
                "tag_picture":"https://i3.yongche.name/media/g3/M04/01/24/rBEDAlt-NKuIR_sBAAIy9jxykZYAAAncQAJZO4AAjMO188.png",
                "show_name":"",
                "recharge":400,
                "activity_id":1053,
                "tag_order":4,
                "percent":40,
                "otherRewards":""
            },
            {
                "tag_id":4452,
                "tag_banner":"",
                "tag_picture":"https://i2.yongche.name/media/g3/M03/01/24/rBEDA1t8-QeIT13iAAI2Y9ZXP1AAAAnHAPygsMAAjZ7859.png",
                "show_name":"",
                "recharge":900,
                "activity_id":1053,
                "tag_order":7,
                "percent":40,
                "otherRewards":""
            },
            {
                "tag_id":4453,
                "tag_banner":"",
                "tag_picture":"https://i1.yongche.name/media/g3/M03/01/24/rBEDA1t8-RuIa-BiAAIzbPiDLw8AAAnIgDLlO4AAjOE865.png",
                "show_name":"",
                "recharge":600,
                "activity_id":1053,
                "tag_order":5,
                "percent":40,
                "otherRewards":""
            },
            {
                "tag_id":4454,
                "tag_banner":"",
                "tag_picture":"https://i2.yongche.name/media/g3/M03/01/24/rBEDAlt8-T2IZlrOAAIxalR0dkQAAAnIgExLxgAAjGC265.png",
                "show_name":"",
                "recharge":800,
                "activity_id":1053,
                "tag_order":6,
                "percent":40,
                "otherRewards":""
            },
            {
                "tag_id":4455,
                "tag_banner":"",
                "tag_picture":"https://i3.yongche.name/media/g4/M02/01/24/rBEDBVt8-WiISuImAAIxk9FSSqcAAAnGQP2QyoAAjGr721.png",
                "show_name":"",
                "recharge":1000,
                "activity_id":1053,
                "tag_order":8,
                "percent":40,
                "otherRewards":""
            },
            {
                "levels":[
                    {
                        "min_price":0,
                        "max_price":100,
                        "percent":0,
                        "tag_banner":"",
                        "otherReward":""
                    },
                    {
                        "min_price":600,
                        "max_price":1000,
                        "percent":40,
                        "tag_banner":"",
                        "otherReward":""
                    },
                    {
                        "min_price":100,
                        "max_price":200,
                        "percent":40,
                        "tag_banner":"",
                        "otherReward":""
                    },
                    {
                        "min_price":200,
                        "max_price":600,
                        "percent":40,
                        "tag_banner":"",
                        "otherReward":""
                    }
                ],
                "tag_id":4456,
                "tag_banner":"",
                "tag_picture":"https://i2.yongche.name/media/g3/M04/01/24/rBEDAlt-MmWIJ6_CAAITKh-5SZAAAAnawKaI8oAAhNC013.png",
                "show_name":"",
                "recharge":0,
                "activity_id":1053,
                "tag_order":9,
                "percent":0,
                "otherRewards":""
            }
        ],
        "no_rebate_price":100,
        "project_document":null,
        "rebate_money_limit":1
    }
}



		// //以下字段值,"充值"改为"购卡"后暂时未使用
        //this.document = result.project_document; 
        //this.minRebateCharge = result.no_rebate_price;   
        //this.is_rebate_money_limit = result.is_rebate_money_limit;  
        //this.rebate_money_limit = result.rebate_money_limit; 
        //this.result.is_join_rebate = result.result.is_join_rebate; 
        //if(result.is_join_rebate==0||result.is_join_rebate==2){
        //    this.isNewUser=true; 
        //} else{
        //    this.isNewUser=false; 
        //}